live_config_reload = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
# draw_bold_text_with_bright_colors = true
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 3

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 6

[mouse]
hide_when_typing = true
# save_to_clipboard = true

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/bin/zsh"

[window]
# decoration = "buttonless"
dynamic_padding = true
dynamic_title = true
opacity = 0.9
startup_mode = "Windowed"

[window.padding]
x = 2
y = 2

